const CREATE_NEW_BOARD = 'CREATE_NEW_BOARD';
const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
const DELETE_TASK = 'DELETE_TASK';
const EDIT_TASK_NAME = 'EDIT_TASK_NAME';
const ADD_TASK_DESCRIPTION = 'ADD_TASK_DESCRIPTION';
const ADD_TASK_PRIORITY = 'ADD_TASK_PRIORITY';
const ADD_TASK_CHECKLIST = 'ADD_TASK_CHECKLIST';
const EDIT_TASK_CHECKLIST_NAME = 'EDIT_TASK_CHECKLIST_NAME';
const ADD_TASK_CHECKLIST_SUB_ITEM = 'ADD_TASK_CHECKLIST_SUB_ITEM';
const UPDATE_STATUS_TASK_CHECKLIST_SUB_ITEM = 'UPDATE_STATUS_TASK_CHECKLIST_SUB_ITEM';
const DELETE_TASK_CHECKLIST_SUB_ITEM = 'DELETE_TASK_CHECKLIST_SUB_ITEM';
const EDIT_TASK_CHECKLIST_SUB_ITEM_NAME = 'EDIT_TASK_CHECKLIST_SUB_ITEM_NAME';
const DELETE_CHECKLIST = 'DELETE_CHECKLIST';

const REORDER_COLUMN = 'REORDER_COLUMN';
const REORDER_BETWEEN_COLUMN = 'REORDER_BETWEEN_COLUMN';

const OPEN_MODAL_CREATE_BOARD = 'OPEN_MODAL_CREATE_BOARD';
const CLOSE_MODAL_CREATE_BOARD = 'CLOSE_MODAL_CREATE_BOARD';

export {
    CREATE_NEW_BOARD,
    CREATE_NEW_TASK,
    DELETE_TASK,
    EDIT_TASK_NAME,
    ADD_TASK_DESCRIPTION,
    ADD_TASK_PRIORITY,
    ADD_TASK_CHECKLIST,
    EDIT_TASK_CHECKLIST_NAME,
    ADD_TASK_CHECKLIST_SUB_ITEM,
    UPDATE_STATUS_TASK_CHECKLIST_SUB_ITEM,
    DELETE_TASK_CHECKLIST_SUB_ITEM,
    EDIT_TASK_CHECKLIST_SUB_ITEM_NAME,
    DELETE_CHECKLIST,

    REORDER_COLUMN,
    REORDER_BETWEEN_COLUMN,

    OPEN_MODAL_CREATE_BOARD,
    CLOSE_MODAL_CREATE_BOARD,
}